Webnovel/Entities/Comic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Webnovel.Entities
{
	public class Comic
	{
		[DatabaseGenerated(DatabaseGeneratedOption.Identity)]
		public int Id
		{
			get;
			set;
		}

		public string Title
		{
			get;
			set;
		}

		public string Description
		{
			get;
			set;
		}

		public string CoverPageImageUrl
		{
			get;
			set;
		}

		public int AuthorId
		{
			get;
			set;
		}

		[ForeignKey("AuthorId")]
		public Author Author
		{
			get;
			set;
		}

		public int CategoryId
		{
			get;
			set;
		}

		public DateTime DateCreated
		{
			get;
			set;
		}

		[ForeignKey("CategoryId")]
		public Category Category
		{
			get;
			set;
		}
        public string Language
        {
            get;
            set;
        }

        public string LeadingGender
        {
            get;
            set;
        }

        public string WariningNotice
        {
            get;
            set;
        }

        public string AudienceAge
        {
            get;
            set;
        }

     
        public ICollection<Episode> Episodes
		{
			get;
			set;
		}

		public ICollection<ComicScene> ComicScenes
		{
			get;
			set;
		}
        public ICollection<ComicTag> Tags
        {
            get;
            set;
        }
        public ICollection<ComicRating> ComicRatings
		{
			get;
			set;
		}
	}
}

Webnovel/Controllers/ComicController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ReflectionIT.Mvc.Paging;
using Webnovel.Components;
using Webnovel.DtoModels;
using Webnovel.Entities;
using Webnovel.Helpers;
using Webnovel.Models;
using Webnovel.Repository;
using Webnovel.Services;
using X.PagedList;

namespace Webnovel.Controllers
{
	[Authorize]
	public class ComicController : Controller
	{
		private UserManager<ApplicationUser> _userManager;

		private string userId;

		private IComic _comic;

		private IAuthor _author;
        private IComicHistory _comicHistory;
        private readonly IPayment _payment;
        private readonly IRate _rate;
        private readonly IComicComment _comment;

        public ComicController(UserManager<ApplicationUser> userManager, IComic comic, IAuthor author,
            IComicHistory comicHistory, IPayment payment, IRate rate 
            , IComicComment comment
            )
			
		{
			_comic = comic;
			_userManager = userManager;
			_author = author;
            _comicHistory = comicHistory;
            _payment = payment;
            _rate = rate;
            _comment = comment;
        }

		public async Task<IActionResult> Create()
		{
			userId = _userManager.GetUserId(User);
			ViewBag.Author = "";
			ComicVm i = new ComicVm();
			if (!(await _author.AuthorExist(userId)))
			{
				ViewBag.Author = "false";
			}
			else
			{
				ViewBag.Author = "true";
				i.AuthorId = (await _author.Get(userId)).Id;
			}
			return (IActionResult)(object)((Controller)this).View((object)i);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create(ComicVm comic)
		{
			Webnovel.Entities.Comic mapped = Mapper.Map<Webnovel.Entities.Comic>((object)comic);
			if (ModelState.IsValid)
			{
				await _comic.CreateComic(mapped);
				if (await _comic.Save())
				{
					ComicVm data = Mapper.Map<ComicVm>((object)mapped);
                    ICollection<string> nTags = comic.NTags;
                    List<ComicTag> novelTag = new List<ComicTag>();
                    if (nTags != null)
                    {
                        foreach (string t in nTags)
                        {
                            if (!(await _comic.FindTag(t)))
                            {
                                await _comic.AddTag(new Tag
                                {
                                    Name = t
                                });
                                await _comic.Save();
                            }
                            Tag tag = await _comic.GetTag(t);
                            if (tag != null)
                            {
                                novelTag.Add(new ComicTag
                                {
                                    ComicId = data.Id,
                                    TagId = tag.Id
                                });
                                await _comic.Save();
                            }
                        }
                    }
                    //create scene 
                  await  _comic.CreateComicScene(new ComicScene()
                    {
                        ComicId = data.Id,
                        Title = "First Scence"
                    });
                  await _comic.Save();
                    return (IActionResult)(object)((Controller)this).Json((object)new
					{
						status = 200,
						message = "Check your entries",
						data = data
					});
				}
			}
            IEnumerable<ModelError> errors = ModelState.Values.SelectMany(v => v.Errors).ToList();
			return (IActionResult)(object)((Controller)this).Json((object)new
			{
				status = 500,
				errors = errors,
				message = "Check your entries"
			});
		}

		public async Task<IActionResult> CoverPage(int id)
		{
			Webnovel.Entities.Comic comic = await _comic.GetComic(id);
			if (comic != null)
			{
				CoverPageVm coverPageVm = new CoverPageVm
				{
					Id = comic.Id
				};
				return (IActionResult)(object)((Controller)this).View((object)coverPageVm);
			}
			return (IActionResult)(object)((Controller)this).View("Error404");
		}

		[HttpPost]
		public async Task<IActionResult> CoverPage(CoverPageVm m)
		{
			if (ModelState.IsValid)
			{
				Webnovel.Entities.Comic comic = await _comic.GetComic(m.Id);
				if (comic == null)
				{
					return (IActionResult)(object)((Controller)this).Json((object)new
					{
						status = 401,
						message = "The Comic You are tring to update does not exist"
					});
				}
				if (!(await CloudinaryUpload.UploadToCloud(m.ImageData)))
				{
					return (IActionResult)(object)((Controller)this).Json((object)new
					{
						status = 500,
						message = "Something went wrong cant upload image now"
					});
				}
				if (comic.CoverPageImageUrl != null)
				{
					await CloudinaryUpload.DeleteFromCloud(comic.CoverPageImageUrl);
				}
				ComicVm comicVm = new ComicVm
				{
					Id = comic.Id,
					CategoryId = comic.CategoryId,
					AuthorId = comic.AuthorId,
					Title = comic.Title,
					Description = comic.Description,
					CoverPageImageUrl = CloudinaryUpload.uploadedPath
				};
				Mapper.Map<ComicVm, Webnovel.Entities.Comic>(comicVm, comic);
				if (await _comic.Save())
				{
					return (IActionResult)(object)((Controller)this).Json((object)new
					{
						status = 200,
						data = m,
						message = "Comic Was Successful"
					});
				}
			}
            IEnumerable<ModelError> errors = ModelState.Values.SelectMany(v => v.Errors).ToList();
			return (IActionResult)(object)((Controller)this).Json((object)new
			{
				status = 500,
				errors = errors,
				message = "Check your entries"
			});
		}

		public async Task<IActionResult> Manage(int id)
		{
			Webnovel.Entities.Comic comic = await _comic.GetComic(id);
			if (comic == null)
			{
				return (IActionResult)(object)((Controller)this).View("Error404");
			}
			return (IActionResult)(object)((Controller)this).View((object)comic);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> AddSceneAsync(ComicSceneVm m)
		{
			if (!(await _comic.FindComic(m.ComicId)))
			{
				return (IActionResult)(object)((Controller)this).Json((object)new
				{
					status = 401,
					message = "Novel Not Found"
				});
			}
			ComicScene mapped = Mapper.Map<ComicScene>((object)m);
			if (ModelState.IsValid)
			{
				await _comic.CreateComicScene(mapped);
				if (await _comic.Save())
				{
					ComicSceneVm data = Mapper.Map<ComicSceneVm>((object)mapped);
					return (IActionResult)(object)((Controller)this).Json((object)new
					{
						status = 200,
						message = "Created Successfully",
						data = data
					});
				}
			}
            IEnumerable<ModelError> errors = ModelState.Values.SelectMany(v => v.Errors).ToList();
			return (IActionResult)(object)((Controller)this).Json((object)new
			{
				status = 400,
				errors = errors,
				message = "Check your entries"
			});
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> AddEpisodeAsync(EpisodeVm m)
		{
			if (!(await _comic.FindComic(m.ComicId)))
			{
				return (IActionResult)(object)((Controller)this).Json((object)new
				{
					status = 401,
					message = "Novel Not Found"
				});
			}
			Episode mapped = Mapper.Map<Episode>((object)m);
			if (ModelState.IsValid)
			{
                // get first scene
                var scene = await _comic.GetComicScenes(m.ComicId);
                if (scene.Any())
                {
                    // 
                  var firstScene =  scene.FirstOrDefault();
                  mapped.ComicSceneId = firstScene.Id;
                }
              
				await _comic.CreateEpisode(mapped);
				if (await _comic.Save())
				{
					EpisodeVm data = Mapper.Map<EpisodeVm>((object)mapped);
					return (IActionResult)(object)((Controller)this).Json((object)new
					{
						status = 200,
						message = "Created Successfully",
						data = data
					});
				}
			}
            IEnumerable<ModelError> errors = ModelState.Values.SelectMany(v => v.Errors).ToList();
			return (IActionResult)(object)((Controller)this).Json((object)new
			{
				status = 400,
				errors = errors,
				message = "Check your entries"
			});
		}

		public async Task<IActionResult> List()
		{
			userId = _userManager.GetUserId(User);
			Webnovel.Entities.Author author = await _author.Get(userId);
			if (author != null)
			{
				return (IActionResult)(object)((Controller)this).View((object)(await _comic.GetAuthorComics(author.Id)));
			}
			return (IActionResult)(object)((Controller)this).View((object)(await _comic.GetAuthorComics(0)));
		}

		public async Task<IActionResult> DeleteComicAsync(int id)
		{
			if (!(await _comic.FindComic(id)))
			{
				return (IActionResult)(object)((Controller)this).Json((object)new
				{
					status = 401,
					message = "novel not found"
				});
			}
			await _comic.DeleteComic(id);
			if (await _comic.Save())
			{
				return (IActionResult)(object)((Controller)this).Json((object)new
				{
					status = 200,
					message = "Deleted Successfully"
				});
			}
			return (IActionResult)(object)((Controller)this).Json((object)new
			{
				status = 400,
				message = "novel not found"
			});
		}

		[HttpPost]
		public async Task<IActionResult> ChangePicture(int episodeId, string imgData)
		{
			if (!(await _comic.FindEpisode(episodeId)))
			{
				return (IActionResult)(object)((Controller)this).Json((object)new
				{
					status = 401,
					message = "Episode not found"
				});
			}
			if (imgData == null)
			{
				return (IActionResult)(object)((Controller)this).Json((object)new
				{
					status = 401,
					message = "No Image Found"
				});
			}
			Episode episode = await _comic.GetEpisode(episodeId);
			if (await CloudinaryUpload.UploadToCloud(imgData))
			{

Webnovel/Views/Comic/CoverPage.cshtml
@using Webnovel.Services
@model Webnovel.Models.CoverPageVm

@{
    ViewData["Title"] = "Comic Cover Page";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Update Cover Picture </h3>
                <div class="row">

                    <div class="col-md-12">
                        <a href="@Url.Action("Manage", "Comic", new {id = Model.Id} )">Manage Comic</a>

                        <label class="control-label"> Upload Cover Page </label>
                        <span class="text text-info">   Click to Begin Upload (max 20 mb) </span> <br />
                        <button class="btn btn-outline-cyan form-control btn-background" id="beginUpload" style="padding: 2.4rem" type="button">
                            <i class="mdi mdi-camera"></i>
                        </button>
                        <span id="txtUploadSuccess" class="text-info"></span>
                        <input type="hidden" id="uploadedUrl" />
                        <input type="hidden" asp-for="Id" id="comicId" />
                    </div>
                    @*<div class="col-sm-8">

                            <form asp-action="CoverPage" id="coverPageForm">
                                <input type="hidden" asp-for="Id" />
                                <input type="hidden" asp-for="ImageData" id="imgData" />
                                <div class="alert alert-warning hide" id="alertNovelError">

                                </div>
                                <div id="show-image" style="width: 200px; display: none">
                                    <img class="img-upload img-fluid" id="item-img-output" src="" />
                                </div>
                                    <img src="~/images/loading.gif" width="40" class="hide img-fluid" id="novelLoading" />
                                    <button type="submit" id="submitButton" class="btn btn-primary"> upload picture </button>
                            </form>


                        </div>*@

                </div>
            </div>
        </div>
    </div>
</div>

@section css{
    <link href="~/admin/assets/libs/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet">
    <link href="~/admin/assets/libs/toastr/build/toastr.min.css" rel="stylesheet">

    <link href="~/css/croppie.css" rel="stylesheet" />
    <style>
        .img-1 {
            /*width: 994px;
            height: 1528px;
            padding-bottom: 25px;*/
        }
    </style>
    <style>

        .btn-background {
            height: 250px;
            width: 200px;
            background-size: contain;
            background-repeat: no-repeat;
            background-position: right;
            background-attachment: local;
        }
    </style>
}

@section Scripts{
    <script src="~/admin/assets/libs/sweetalert2/dist/sweetalert2.all.min.js"></script>
    <script src="~/js/croppie.min.js"></script>
    <script src="~/admin/assets/libs/toastr/build/toastr.min.js"></script>

    <script>
        var $uploadCrop,
            tempFilename,
            rawImg,
            imageId;
        function readFile(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    //$('.upload-demo').addClass('ready');
                    //$('#cropImagePop').modal('show');
                    rawImg = e.target.result;
                    $('#item-img-output').attr('src', rawImg);
                    $('#imgData').val(rawImg);
                    $('#show-image').show();

                }
                reader.readAsDataURL(input.files[0]);
            }
            else {
                swal("Sorry - you're browser doesn't support the FileReader API");
            }
        }


        $('#uploadFile').on('change', function () {
            imageId = $(this).data('id');
            tempFilename = $(this).val();
            //$('#cancelCropBtn').data('id', imageId);
            readFile(this);
        });

            //$('#cropImageBtn').on('click', function (ev) {
            //    $uploadCrop.croppie('result', {
            //        //type: 'base64',
            //        type: 'rawcanvas',

            //        format: 'jpeg',
            //        //size: {width: 150, height: 200}
            //    }).then(function (resp) {
            //        $('#item-img-output').attr('src', resp.toDataURL());
            //        //$('#cropImagePop').modal('hide');
            //        console.log(resp);
            //    });
            //});

        $("#coverPageForm").submit(function(event) {
            event.preventDefault();
            var data = $(this).serialize();

            $.ajax({
                url: $(this).attr("action"),
                type: 'POST',
                data: data,
                dataType: 'json',
                beforeSend: function () {
                    $("#submitButton").attr('disabled', 'disabled');
                    $("#novelLoading").show(); 
                    toastr.success("Saving Changes");

                },
                complete: function(){
                    $("#submitButton").removeAttr('disabled');
                    $("#novelLoading").hide();

                },
                success: function (response) {
                    if (response.status == 200) {
                        //$("#createAuthorModal").modal('hide');
                        //$('#alertError').addClass('hide');
                        //$('#authorId').val(response.data.id);

                        Swal.fire({
                            title: 'Success',
                            text: 'Upload was Successful',
                            type: 'success',
                            confirmButtonText: 'Cool'
                        });
                        var url = "@Url.Action("Manage","Comic", new {id= Model.Id})";
                        location.href = url;
                        console.log(response);
                    } else {
                        $("#alertNovelError").text(response.message);
                        $('#alertNovelError').removeClass('hide');

                    }
                    console.log(response);
                },
                error: function(err) {
                    console.log(err);
                }

            });
        });

    </script>

    <script src="https://widget.cloudinary.com/v2.0/global/all.js" type="text/javascript">
    </script>



    <script>
        var cloudName = "@CloudinaryUpload.cloud";
        var apiKey = "@CloudinaryUpload.apiKey";
        var widget = cloudinary.createUploadWidget({
                cloudName: cloudName,
                apiKey: apiKey,
                uploadPreset: "unsignedUpload",
                folder: "webnovel",
                maxFiles: 1,
                resourceType: "image",
                maxFileSize: 21000000
            },
            (error, result) => {
                if (result && result.event === "success") {
                    // do something
                    $("#uploadedUrl").val(result.info.secure_url);
                    $("#beginUpload").css("background-image", "url(" + result.info.secure_url+")");
                    $("#txtUploadSuccess").html("Uploaded Successfully");
                    var data = {
                        id: '@Model.Id',
                        ImageData: result.info.secure_url
                    };

                    $.ajax({
                        url: $(this).attr("action"),
                        type: 'POST',
                        data: data,
                        dataType: 'json',
                        beforeSend: function () {
                            //$("#submitButton").attr('disabled', 'disabled');
                            //$("#novelLoading").show();
                        },
                        //complete: function(){
                        //    $("#submitButton").removeAttr('disabled');
                        //    $("#novelLoading").hide();
                        //},
                        success: function (response) {
                            if (response.status == 200) {
                                //$("#createAuthorModal").modal('hide');
                                //$('#alertError').addClass('hide');
                                //$('#authorId').val(response.data.id);

                                Swal.fire({
                                    title: 'Success',
                                    text: 'Upload was Successful',
                                    type: 'success',
                                    confirmButtonText: 'Cool'
                                });
                                var url = "@Url.Action("Manage","Comic", new {id= Model.Id})";
                                location.href = url;
                                console.log(response);
                            } else {
                                $("#alertNovelError").text(response.message);
                                $('#alertNovelError').removeClass('hide');

                            }
                            console.log(response);
                        },
                        error: function(err) {
                            console.log(err);
                        }

                    });
                }
                console.log(result);
            });

        $("#beginUpload").click(function(event) {
            event.preventDefault();
            widget.open();
        });
    </script>
}

Webnovel/Views/Comic/Library.cshtml
@model System.Collections.Generic.IEnumerable<Webnovel.Entities.ComicLibrary>

@using CloudinaryDotNet
@using Webnovel.Helpers
@using Webnovel.Services

@{
    ViewBag.Title = "My Comic Library";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


@{


    Layout = "~/Views/Shared/_ReaderLayout.cshtml";

    var cloudinary = new Cloudinary(new Account()
    {
        ApiKey = CloudinaryUpload.apiKey,
        ApiSecret = CloudinaryUpload.apiSecret,
        Cloud = CloudinaryUpload.cloud,

    });

}
<div class="row">
    <div class="col-md-12 card">
        <h2 class="card-title p-3"> My Comic Barns</h2>


    </div>
    @foreach (var i in Model)
    {
        var img = i.Comic.CoverPageImageUrl;
        if (img != null)
        {
            img = cloudinary.Api.UrlImgFetch.
                Transform(new Transformation()
                    .Height(300).Width(300).Crop("fill")).BuildUrl(i.Comic.CoverPageImageUrl);

        }
        <div class="col-lg-3 col-md-4">

            <div class="card">
                <div class="el-card-item">
                    <div class="el-card-avatar el-overlay-1">
                        <img src="@img" class="img-fluid" href="@i.Comic.CoverPageImageUrl" alt="user" />

                    </div>
                    <div class="d-flex no-block align-items-center">
                        <div class="m-l-15">
                            <h4 class="m-b-0">   @StringProcessor.SubString(i.Comic.Title, 0, 15)</h4>
                            <span class="text-muted">  @StringProcessor.SubString(i.Comic.Description, 0, 30)</span>
                        </div>

                        <div class="ml-auto m-r-15">
                            <a href="@Url.Action("RemoveFromLibrary", new {id=i.ComicId})" class="btn btn-danger btn-circle"> <i class="fa fa-trash"></i></a>
                        </div>

                    </div>
                    <div>
                        @*<a class="btn default btn-outline image-popup-vertical-fit el-link" href="@i.Comic.CoverPageImageUrl"><i class="icon-magnifier"></i></a>*@
                        <a class="btn btn-primary  default btn-outline el-link" href="@Url.Action("ReadComic", new{id = i.ComicId})"><i class="icon-book-open"></i> Read</a>
                    </div>
                </div>
            </div>
        </div>


    }
</div>

Webnovel/Views/Comic/List.cshtml
@using CloudinaryDotNet
@using Webnovel.Services
@model System.Collections.Generic.List<Webnovel.Entities.Comic>

@{
    ViewBag.Title = "My Comics";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    var cloudinary = new Cloudinary(new Account()
    {
        ApiKey = CloudinaryUpload.apiKey,
        ApiSecret = CloudinaryUpload.apiSecret,
        Cloud = CloudinaryUpload.cloud,

    });

}

@*@section TopScripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cloudinary-core/2.6.3/cloudinary-core-shrinkwrap.min.js" type="text/javascript">
    </script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cloudinary-core/2.6.3/cloudinary-core-shrinkwrap.min.js" type="text/javascript">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/cloudinary-core/2.6.3/cloudinary-core.min.js" type="text/javascript">
    </script>

    <script>
        var cloudName = "@CloudinaryUpload.cloud";
        var apiKey = "@CloudinaryUpload.apiKey";
        var cl = new cloudinary.Cloudinary({ cloud_name: cloudName, secure: true });
    </script>
}*@
<div class="row">
    <div class="col-12">
        <h4 class="d-inline">My Comics</h4>
        <!-- Row -->
        <div class="row">
            @if (Model.Any())
            {
                foreach (var i in Model)
                {
                    <div class="col-lg-3 col-md-3" id="noveList_@i.Id">
                        <!-- Card -->
                        <div class="card"> 
                            @{ 

                                var img = i.CoverPageImageUrl;
                                if (img != null)
                                {
                                    img = cloudinary.Api.UrlImgFetch.
                                        Transform(new Transformation()
                                            .Height(300).Width(300).Crop("fill")).BuildUrl(i.CoverPageImageUrl);
                                    var s = i.CoverPageImageUrl.Insert(45, "w_300,h_200,c_fit/");
                                }
                                else
                                {
                                    
                                    img = "https://comicbookrealm.com/cover-scan/d3459cbd5aaffcd225612beed968dc25/xl/comics-conspiracy-generic-comic-issue-7.jpg";
                                }


                                /*cloudinary.Api.UrlImgUp.Secure(true).
                                    Transform(new Transformation().Width(150).Height(150).Crop("fit")).Format("Jpg").Type("fetch")
                                    .BuildUrl(i.CoverPageImageUrl);*/ }
                            @*<img class="card-img-top img-fluid"src="@i.CoverPageImageUrl" alt="Card image cap">*@
                            <img class="card-img-top img-fluid" src="@img" alt="Card image cap">
                            @*@Html.Raw(img)*@
                       
                            <div class="card-body">
                                <div class="d-flex no-block align-items-center m-b-15">
                                    <span><i class="ti-eye"></i> 0 Views</span>
                                    <div class="ml-auto">
                                        <a href="javascript:void(0)" class="link"><i class="ti-comments"></i> 3 Comments</a>
                                    </div>
                                </div>
                                <h4 class="card-title">@i.Title</h4> 
                                @{
                                    var des = 
                                        !String.IsNullOrWhiteSpace(i.Description) && i.Description.Length >= 50
                                            ? i.Description.Substring(0, 50)
                                            : i.Description;
                                    des += " ...";
                                }
                                <p class="card-text novel-list-des">@des</p>
                                <a class="btn btn-primary waves-effect btn-xs waves-light" href="@Url.Action("Manage", "Comic", new {id = i.Id})"><span class="btn-label"><i class="mdi mdi-settings"></i></span> Manage Contents</a>
                                <button type="button" data-id="@i.Id" data-href="@Url.Action("DeleteComicAsync", new {id = i.Id})" class="btn btn-danger btn-xs waves-effect waves-light deleteNovel"><span class="btn-label"><i class="mdi mdi-delete"></i></span> Delete</button>
                                <a class="waves-effect waves-light" href="@Url.Action("CoverPage", "Comic", new {id = i.Id})"><span class="btn-label"><i class="mdi mdi-image"></i></span> Change Cover Picture</a>

                            </div>
                        </div>
                        <!-- Card -->
                    </div>
                }
            }
            else
            {
                <div class="card">
                    <div class="card-body">
                        <h1>No Comic Yet</h1>
                        <a asp-action="Create" class="btn btn-info"> Create one </a>
                    </div>
                </div>
            }<!-- column -->
            <!-- column -->

        </div>
        <!-- Row -->

    </div>
</div>
@section css{
    <link href="~/admin/assets/libs/sweetalert2/dist/sweetalert2.min.css" rel="stylesheet">
}

@section Scripts
    {
    <script src="~/admin/assets/libs/sweetalert2/dist/sweetalert2.all.min.js"></script>

    <script>
        $(function () {
            $(".novel-list-des").text().substring(0, 100);

            $(".deleteNovel").click(function (event) {
                event.preventDefault();
                var $btn = $(this);
                var url = $(this).attr("data-href");
                var nId = $(this).attr("data-id");
                Swal.fire({
                    title: 'Are you sure?',
                    text: "You won't be able to revert this!",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes, delete it!'
                }).then((result) => {
                    if (result.value) {
                        $.ajax(url,
                            {
                                type: "get",
                                beforeSend: function () {
                                    $(this).attr("disabled", "disabled");
                                },
                                complete: function () {
                                    $(this).removeAttr("disabled");

                                },
                                success: function (response) {
                                    if (response.status == 200) {
                                        Swal.fire(
                                            'Deleted!',
                                            'Your Comic has been deleted.',
                                            'success'
                                        );
                                        $("#noveList_" + nId).remove();

                                    } else {
                                        Swal.fire(
                                            'Error!',
                                            'Something went wrong',
                                            'success'
                                        );
                                    }
                                    console.log(response);
                                },
                                error: function (err) {
                                    console.log(err);
                                }
                            });

                    }
                });

            });

        });
    </script>

}